[tool.poetry]
name = "postfast"
version = "0.3.18"
description = "Learning Path for LangGraph"
authors = ["Evan <evaanngc@gmail.com>"]
readme = "README.md"
packages = [{include = "postfast"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
langchain-core = ">=0.3.35,<0.4.0"
langgraph = ">=0.2.72,<0.3.0"
fastapi = ">=0.115.8,<0.116.0"
langchain-google-genai = ">=0.0.11"
uvicorn = ">=0.34.0,<0.35.0"
langchain-openai = ">=0.3.5,<0.4.0"
python-dotenv = ">=1.0.1,<2.0.0"
langchain = ">=0.3.18,<0.4.0"
pydantic = ">=2.10.6,<3.0.0"
requests = ">=2.32.3,<3.0.0"
langchain-community = ">=0.3.17,<0.4.0"
watchfiles = ">=0.13.0"
cryptography = ">=43.0.3,<44.0.0"

[tool.poetry.group.dev.dependencies]
cmake = ">=3.31.4,<4.0.0"
ninja = ">=1.11.1.3,<2.0.0.0"
scikit-build-core = ">=0.10.7,<0.11.0"
llama-cpp-python = "0.2.90"
mypy = ">=1.11.1"
ruff = ">=0.6.1"
langgraph-api = ">=0.0.30"
langgraph-cli = {version = ">=0.1.73", extras = ["inmem"]}
pytest = ">=8.3.4"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"